---
apiVersion: v1
kind: Service
metadata:
  name: emptyserv
  namespace: traefik
spec:
  type: ClusterIP
  ports:
  - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catchall-503-ingress
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`^.+\.${CLUSTERNAME}\.${DOMAINNAME}$`)
      priority: 1
      services:
        - name: emptyserv
          port: 80
  tls:
    certResolver: le